### ISSUE TITLE
スワイプで行削除

### ISSUE THREAD

**Issue by takuma-2531** [takuma-2531/MultiCounter#12]
スワイプでListの行を削除する。
行を削除というか、対応するRealmDBのデータを削除する。

**Comment by syuu0227** [comment]
ListのonDeleteではRealmの対応するデータを選択するのが難しいと考えられる。
DragGestureで実装できないか検討中。

**Comment by takuma-2531** [comment]
DragGestureで行削除自体はできることをサンプルアプリで確認した。
.onChangedとか.onEndedを使って、左スワイプを検出。
`if value.location.x - value.startLocation.x <= -UIScreen.main.bounds.size.width / 4 { 処理 }`
的な。
ただUIが微妙だから、スワイプしたらダイアログボックス出して削除しますか？YES or NO を出すのが現時点の最適解。

**Comment by takuma-2531** [comment]
あるいは、削除は編集モードオンリーで行う。
編集モードではついでに行の入れ替えとかもできるようにしたい。

**Comment by takuma-2531** [comment]
ListのonDeleteのスワイプでも行を削除する方法はある。
ただ、このアプリでスワイプで行削除を必要とするかは要検討。
