### ISSUE TITLE
端末へのデータ保存の実装（Realm）

### ISSUE THREAD

**Issue by takuma-2531** [takuma-2531/MultiCounter#2]
Realm？CoreData?
SwiftUIでRealmが使えるかの調査。
CoreDataは使えるが根本的な使い方がわからないので、それを勉強する。

**Comment by syuu0227** [comment]
SwiftUIでのRealm使用法を調査中。

**Comment by takuma-2531** [comment]
Realm、1対1の関係なら保存方法が分かった。
ただ、多対1の関係の保存法が未理解なので、それが理解できたら実装に移す。

**Comment by takuma-2531** [comment]
1対多の関係の保存方法がサンプルアプリで実装できた。
コードが最適かどうかは分からないが。
あとは編集や削除の方法を調査して、できるようになったら久々にマルチカウンターに戻って来れる！

**Comment by takuma-2531** [comment]
1対多の編集、削除方法もわかった。
ので、このアプリにRealmを導入する。

**Comment by takuma-2531** [comment]
Realmを使うことに決定。
保存関連はイシューを細かく分けて作成。
Realm関連はイシューのタイトルの最後に（Realm）をつける。
このイシューはクローズ。
